"""The readable YAML view of a playbook (generated with fsr-playbooks' decompiler)."""
import importlib.metadata
import json
import re
import zipfile
from pathlib import Path

import yaml
from fsr_playbooks._db import PACKAGED_SLIM_DB
from fsr_playbooks.compiler import compile_yaml

from soarshelf import review_yaml

SOURCE = """
collection: Demo
description: A demo.
playbooks:
  - name: Check IP
    steps:
      - name: Start
        type: start
        module: alerts
        next: Pick
      - name: Pick
        type: decision
        conditions:
          - display: Public
            when: "{{ vars.input.records[0].sourceIp }}"
            next: Note
          - display: Else
            default: true
            next: Skip
      - name: Note
        type: set_variable
        vars:
          text: "{{ vars.input.records[0].sourceIp }}"
      - name: Skip
        type: set_variable
        vars:
          skipped: true
"""


def _wire(name="Check IP") -> dict:
    res = compile_yaml(SOURCE.replace("Check IP", name), PACKAGED_SLIM_DB)
    assert res.ok, [e.message for e in res.errors if e.severity != "warning"]
    return res.fsr_json


def _item(tmp_path: Path, wire: dict) -> Path:
    item = tmp_path / "pb"
    item.mkdir()
    (item / "playbook.json").write_text(json.dumps(wire))
    return item


def _steps(text: str) -> list[dict]:
    return yaml.safe_load(text)["playbooks"][0]["steps"]


def test_the_view_is_marked_generated_and_reads_as_authoring_yaml(tmp_path):
    text = review_yaml.item_files(_item(tmp_path, _wire()))["playbook.yaml"]
    assert text.startswith("# Review view of playbook.json. Generated by `soarshelf yaml`")
    steps = _steps(text)
    assert [s["name"] for s in steps] == ["Start", "Pick", "Note", "Skip"]
    assert steps[0]["next"] == "pick"
    assert [(c["display"], c["next"]) for c in steps[1]["conditions"]] == [("Public", "note"), ("Else", "skip")]
    assert steps[3]["vars"] == {"skipped": True}


def test_canvas_positions_and_step_uuids_are_left_out(tmp_path):
    steps = _steps(review_yaml.item_files(_item(tmp_path, _wire()))["playbook.yaml"])
    assert not any({"uuid", "top", "left"} & set(s) for s in steps)


def test_long_dashes_are_written_as_hyphens(tmp_path):
    wire = _wire()
    wire["data"][0]["workflows"][0]["steps"][2]["arguments"]["vars"] = {"text": "Done \u2014 ready \u2013 next"}
    text = review_yaml.item_files(_item(tmp_path, wire))["playbook.yaml"]
    assert "\u2014" not in text and "\u2013" not in text
    assert "Done - ready - next" in text


def test_a_hostile_pack_member_name_cannot_write_into_the_view(tmp_path):
    z = tmp_path / "pack.zip"
    with zipfile.ZipFile(z, "w") as zf:
        zf.writestr("export_1/playbooks/Coll\nsteps: []\nname: FAKE/evil.json", json.dumps(_wire()["data"][0]["workflows"][0]))
    item = tmp_path / "pack"
    item.mkdir()
    z.rename(item / "pack.zip")
    (text,) = review_yaml.item_files(item).values()
    head = text.split("\n", 3)
    assert head[0].startswith("# Review view of Coll?steps: []?name: FAKE/evil.json")
    assert all(line.startswith("#") for line in text.splitlines()[:3]), "only comments may precede the YAML"
    assert yaml.safe_load(text)["playbooks"][0]["name"] == "Check IP"       # parses as the real playbook, not the injected lines


def test_it_is_much_shorter_than_the_json(tmp_path):
    wire = _wire()
    view = review_yaml.item_files(_item(tmp_path, wire))["playbook.yaml"]
    assert len(view.splitlines()) < len(json.dumps(wire, indent=2).splitlines()) / 2


def test_two_playbooks_that_slugify_the_same_both_get_a_file(tmp_path):
    z = tmp_path / "pack.zip"
    wf = lambda n: json.dumps(_wire(n)["data"][0]["workflows"][0])  # noqa: E731
    with zipfile.ZipFile(z, "w") as zf:
        zf.writestr("export_1/playbooks/Coll A/Block IP.json", wf("Block IP"))
        zf.writestr("export_1/playbooks/Coll A/Block  IP!.json", wf("Block  IP!"))
        zf.writestr("export_1/playbooks/Coll A/collection.metadata.json", json.dumps({"description": "x"}))
        zf.writestr("export_1/playbooks/tags.json", "[]")
        zf.writestr("export_1/info.json", "{}")
    item = tmp_path / "pack"
    item.mkdir()
    z.rename(item / "pack.zip")
    files = review_yaml.item_files(item)
    assert sorted(files) == ["playbooks/coll_a/block_ip.yaml", "playbooks/coll_a/block_ip_2.yaml"]
    assert yaml.safe_load(files["playbooks/coll_a/block_ip.yaml"])["collection"] == "Coll A"


def test_a_playbook_that_will_not_render_is_noted_not_fatal(tmp_path):
    item = _item(tmp_path, {"type": "workflow_collections", "data": [{"workflows": "not a list"}]})
    text = review_yaml.item_files(item)["playbook.yaml"]
    assert "NO VIEW" in text and "Review playbook.json directly" in text and text.startswith("# Review view")


def test_sync_writes_then_check_passes_then_detects_staleness_and_removes_orphans(tmp_path):
    item = _item(tmp_path, _wire())
    assert review_yaml.sync_item(item, check=True) == ["playbook.yaml"]
    assert review_yaml.sync_item(item) == ["playbook.yaml"]
    assert review_yaml.sync_item(item, check=True) == []
    (item / "playbook.yaml").write_text("# hand edited\n")
    assert review_yaml.sync_item(item, check=True) == ["playbook.yaml"]
    (item / "playbooks").mkdir()
    (item / "playbooks" / "old.yaml").write_text("x")
    assert "playbooks/old.yaml" in review_yaml.sync_item(item)
    assert not (item / "playbooks").exists()


def test_the_committed_views_match_the_committed_json():
    content = Path(__file__).resolve().parents[2] / "content"
    assert review_yaml.sync_content(content, check=True) == [], "run `soarshelf yaml` in the pipeline venv and commit"


def test_views_are_generated_with_the_pinned_fsr_playbooks():
    """A different release can word things differently and mark every view stale, so the pin is the contract."""
    pin = re.search(r'"fsr-playbooks==([^"]+)"', (Path(__file__).resolve().parents[1] / "pyproject.toml").read_text())
    assert pin, "pyproject.toml must pin fsr-playbooks exactly"
    assert importlib.metadata.version("fsr-playbooks") == pin.group(1), "use the pipeline venv (uv pip install -e '.[test]')"
