"""A readable YAML view of each playbook, committed next to the JSON so a reviewer can see what it does.

The export JSON is hundreds of lines of ids, coordinates and iris. This is the same playbook in the
authoring YAML that ``fsr-playbooks`` decompiles to (``fsrpb decompile``): one block per step, with what
it does and where it goes next, without the canvas positions and uuids. It is generated from
``playbook.json`` / ``pack.zip`` by ``soarshelf yaml``, CI fails if one is stale, and the JSON stays the
source of truth: the view is for reading, and a playbook should be installed from the JSON.

The packaged catalog that ships in the ``fsr-playbooks`` wheel is all the decompiler needs. It only uses
the catalog to drop values the compiler would put back, so the output is the same as with a full probed
reference database.
"""
from __future__ import annotations

import json
import re
import zipfile
from pathlib import Path
from typing import Any

import yaml
from fsr_playbooks._db import PACKAGED_SLIM_DB
from fsr_playbooks.compiler.decompiler import decompile_to_yaml

MAX_MEMBER = 10 * 1024 * 1024

HEADER = (
    "# Review view of {source}. Generated by `soarshelf yaml`; edits are overwritten.\n"
    "# For reading: install the playbook from the JSON, which is the source of truth.\n"
    "# Long dashes are written as hyphens here.\n"
)


def _slug(text: str) -> str:
    s = re.sub(r"[^a-z0-9]+", "_", text.lower()).strip("_")
    return s or "playbook"


def _hyphens(text: str) -> str:
    """En and em dashes become hyphens: they break FortiSOAR's latin-1 connector encoding if a view is ever
    copied into a playbook, and the repo's commit hook refuses them. The JSON keeps the original text."""
    return text.replace("\u2013", "-").replace("\u2014", "-")


def _without_layout(text: str) -> str:
    """Drop each step's canvas position and uuid. The same result as ``decompile_to_yaml(layout=False)``,
    which is not in every released fsr-playbooks yet; it ends in the same ``safe_dump`` call."""
    doc = yaml.safe_load(text)
    for pb in doc.get("playbooks") or []:
        for step in pb.get("steps") or []:
            for key in ("uuid", "top", "left"):
                step.pop(key, None)
    return yaml.safe_dump(doc, sort_keys=False, allow_unicode=True)


def _render(export: dict[str, Any], source: str) -> str:
    try:
        body = _hyphens(_without_layout(decompile_to_yaml(export, PACKAGED_SLIM_DB)))
    except Exception as exc:  # noqa: BLE001 - one odd playbook must not stop a submission being filed
        return HEADER.format(source=source) + f"# No view: it could not be rendered ({type(exc).__name__}).\n"
    return HEADER.format(source=source) + body


def _wrap(workflow: dict[str, Any], name: str, description: str) -> dict[str, Any]:
    """A bare workflow file from a solution pack, as the one-playbook collection the decompiler reads."""
    return {"type": "workflow_collections", "macros": [], "exported_tags": [],
            "data": [{"@type": "WorkflowCollection", "name": name, "description": description, "visible": True,
                      "workflows": [workflow]}]}


# --- what to generate for a content item -------------------------------------------------------

def _pack_files(zf: zipfile.ZipFile) -> dict[str, str]:
    """``playbooks/<collection>/<playbook>.yaml`` for every workflow in a solution pack."""
    out: dict[str, str] = {}
    meta: dict[str, str] = {}
    for name in zf.namelist():
        parts = name.split("/")
        if len(parts) == 4 and parts[1] == "playbooks" and parts[3] == "collection.metadata.json":
            try:
                meta[parts[2]] = str(json.loads(zf.read(name)).get("description") or "")
            except ValueError:
                pass
    for name in sorted(zf.namelist()):
        parts = name.split("/")
        if len(parts) != 4 or parts[1] != "playbooks" or not name.endswith(".json") or parts[3] == "collection.metadata.json":
            continue
        if zf.getinfo(name).file_size > MAX_MEMBER:          # the pipeline rebuilt this zip; still never trust sizes
            continue
        try:
            wf = json.loads(zf.read(name))
        except ValueError:
            continue
        base = f"playbooks/{_slug(parts[2])}/{_slug(str(wf.get('name') or parts[3][:-5]))}"
        path, n = f"{base}.yaml", 1
        while path in out:                  # two names that slugify the same: keep both, in a stable order
            n += 1
            path = f"{base}_{n}.yaml"
        out[path] = _render(_wrap(wf, parts[2], meta.get(parts[2], "")), f"{parts[2]}/{parts[3]}")
    return out


def item_files(item: Path) -> dict[str, str]:
    """Relative path -> YAML text that this content item should carry."""
    pj = item / "playbook.json"
    if pj.is_file():
        return {"playbook.yaml": _render(json.loads(pj.read_text()), "playbook.json")}
    pz = item / "pack.zip"
    if pz.is_file():
        with zipfile.ZipFile(pz) as zf:
            return _pack_files(zf)
    return {}


def _existing(item: Path) -> set[str]:
    found = {"playbook.yaml"} if (item / "playbook.yaml").is_file() else set()
    base = item / "playbooks"
    if base.is_dir():
        found |= {str(p.relative_to(item)) for p in base.rglob("*.yaml")}
    return found


def sync_item(item: Path, check: bool = False) -> list[str]:
    """Write (or, with ``check``, only compare) the YAML for one item. Returns what is out of date."""
    want = item_files(item)
    stale: list[str] = []
    for rel, text in want.items():
        p = item / rel
        if not p.is_file() or p.read_text() != text:
            stale.append(rel)
            if not check:
                p.parent.mkdir(parents=True, exist_ok=True)
                p.write_text(text)
    for rel in sorted(_existing(item) - set(want)):       # a playbook that no longer exists
        stale.append(rel)
        if not check:
            (item / rel).unlink()
    if not check and (item / "playbooks").is_dir():
        base = item / "playbooks"
        for d in sorted(base.rglob("*"), reverse=True) + [base]:
            if d.is_dir() and not any(d.iterdir()):
                d.rmdir()
    return stale


def sync_content(content: Path, check: bool = False) -> list[str]:
    stale: list[str] = []
    for kind in ("playbooks", "solution-packs"):
        base = content / kind
        for item in sorted(p for p in base.iterdir() if p.is_dir()) if base.is_dir() else []:
            stale += [f"{kind}/{item.name}/{rel}" for rel in sync_item(item, check)]
    return stale
